apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-fake-student
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: adapter-fake-student
  template:
    metadata:
      labels:
        app: adapter-fake-student
    spec:
      restartPolicy: Always
      containers:
        - name: adapter-fake-student
          image: fintlabs.azurecr.io/fake-student-adapter:1.0.1
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 8091
          readinessProbe:
            httpGet:
              path: /health
              port: 8091
            initialDelaySeconds: 60
            timeoutSeconds: 5
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:+ExitOnOutOfMemoryError -Xmx1G -verbose:gc'
            - name: springfox.title
              value: 'Fake fake-student Adapter'
            - name: security.basic.enabled
              value: 'false'
            - name: fint.adapter.organizations
              value: fake.fintlabs.no
            - name: fint.adapter.fake.students
              value: '2000'
            - name: fint.adapter.fake.groups
              value: '200'
            - name: fint.adapter.endpoints.providers.elev
              value: https://beta.felleskomponent.no/utdanning/elev/provider
            - name: fint.adapter.endpoints.providers.utdanningsprogram
              value: https://beta.felleskomponent.no/utdanning/utdanningsprogram/provider
            - name: fint.adapter.endpoints.providers.timeplan
              value: https://beta.felleskomponent.no/utdanning/timeplan/provider
            - name: fint.oauth.enabled
              value: "true"
            - name: fint.oauth.request-url
              value: https://beta.felleskomponent.no
            - name: fint.oauth.access-token-uri
              value: https://idp.felleskomponent.no/nidp/oauth/nam/token
            - name: fint.oauth.scope
              value: fint-client
            - name: fint.oauth.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: fake-adapter
            - name: fint.oauth.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: fake-adapter
            - name: fint.oauth.username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: fake-adapter
            - name: fint.oauth.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: fake-adapter
