server:
 port: 8091

springfox:
 title: '@title@'
 version: '@version@'

base-url: https://play-with-fint.felleskomponent.no/utdanning/elev/provider
fint:
 adapter:
  organizations: fake.no
  sse-endpoint: ${base-url}/sse/%s
  status-endpoint: ${base-url}/status
  response-endpoint: ${base-url}/response

 oauth:
  enabled: false
  access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
  scope: fint-client
