security:
 basic:
  enabled: false

fint:
 adapter:
  organizations: mock.no
  endpoints:
   providers:
    elev: http://localhost:8081/provider
  fake:
   students: 20000
   groups: 2000
 oauth:
  enabled: false

server:
 port: 8092
